export const ADD_ARTICLE = 'ADD_ARTICLE';
export const FOUND_BAD_WORD = 'FOUND_BAD_WORD';
export const DATA_LOADING_BEGIN = 'DATA_LOADING_BEGIN';
export const DATA_LOADING_SUCCESS = 'DATA_LOADING_SUCCESS';
export const DATA_LOADING_FAILURE = 'DATA_LOADING_FAILURE';
